### ISSUE TITLE
position of minimap

### ISSUE THREAD

**Issue by AquaJerry** [andrzejkrecicki/epoch-of-emperors#1]
Currently your minimap is out of container.
```html
<!-- index.html (runtime) -->

<body>
  <div id="container" style="width: 800px; height: 600px;">
    ...
  </div>
  ...
  <canvas width="128" height="128" class="tmpMiniMap"></canvas>
</body>
```
which is caused by
```js
// src/viewer.js

class MapDrawable extends Graphics.Node {
    ...
    insertTiles() {
        let miniCanv = document.createElement("canvas");
        ...
        document.body.appendChild(miniCanv);
    }
    ...
}
```
And its position is based on `<body>` instead of the container.
```html
<!-- index.html -->

<style type="text/css">
    ...
    body > canvas.tmpMiniMap {
        ...
        position: absolute;
        ...
    }
</style>
```
So here's my solution to fix its position.
```diff
--- a/index.html
+++ b/index.html
@@ -14,12 +14,10 @@
         #debugInfo {
             white-space: pre;
         }
-        body > canvas.tmpMiniMap {
+        .tmpMiniMap {
             transform: rotateX(60deg) rotateZ(-45deg) scale(1.2);
-            position: absolute;
-            top: 409px;
-            left: 556px;
-            margin: 70px;
+            bottom: 1px;
+            right: 54px;
         }
     </style>
 </head>
```
```diff
--- a/src/viewer.js
+++ b/src/viewer.js
@@ -284,7 +284,7 @@ class MapDrawable extends Graphics.Node {
         }
 
         miniCanv.className = "tmpMiniMap";
-        document.body.appendChild(miniCanv);
+        this.stage.container.appendChild(miniCanv);
     }
     tileCoordsToScreen(tx, ty) {
         let H = MapDrawable.TILE_SIZE.height;
```

**Comment by andrzejkrecicki** [comment]
Hello AquaJerry!

I am delighted to see the first issue in my repository! Thank you. I really appreciate all the effort you put in cloning this project and analyzing all its code without any guide or documentation.

I admit that you are correct - mini map is outside the game container. It should not be like this although as its class name indicates tmpMiniMap is just a makeshift substitute of a real map which will be created at some point together with its all missing features.

Your solution is fine although it tangles mouse events because so far I believed that every child of container will be of the same size and position. You can see incorrect viewport sideways panning when you move mouse around minimap.

First of all you might have to delete your local copy of this repository and clone it again because in the meantime I did a force push therefore git will fail to pull and push... I am really sorry about that. Usually I don't do force pushes. This will never happen since this repository got first attention from others and I don't want to mess with their copies.

To fix the mouse events issue you will need to add some modifications:
```diff
--- a/index.html
+++ b/index.html
@@ -3,6 +3,10 @@
 <head>
     <title>Epoch of Emperors</title>
     <style type="text/css">
+        body, html {
+            padding: 0px;
+            margin: 0px;
+        }
         #container canvas {
             border: none !important;
             position: absolute;
```

```diff
--- a/src/graphics/graphics.js
+++ b/src/graphics/graphics.js
@@ -201,8 +201,8 @@ class Stage extends Node {
         this.dispatch("click", e);
     }
     dispatch(type, e) {
-        let x = e.offsetX;
-        let y = e.offsetY;
+        let x = e.clientX;
+        let y = e.clientY;
         for (let i = this.children.length - 1; i > -1; --i) {
             let node = this.children[i].getNodeAt(x, y);
             if (node) {
@@ -212,8 +212,8 @@ class Stage extends Node {
         }
     }
     mousemove(e) {
-        let x = e.offsetX;
-        let y = e.offsetY;
+        let x = e.clientX;
+        let y = e.clientY;
         for (let i = this.children.length - 1; i > -1; --i) {
             let node = this.children[i].getNodeAt(x, y);
             this.mouse.x = x;
```

```diff
--- a/src/viewer.js
+++ b/src/viewer.js
@@ -158,8 +165,8 @@ class GameViewer {
         }
     }
     handleMouseMove(e) {
-        this.mouseX = e.evt.layerX;
-        this.mouseY = e.evt.layerY;
+        this.mouseX = e.evt.clientX;
+        this.mouseY = e.evt.clientY;
     }
     handleScroll() {
         if (this.mouseX < 30) {
```

After that I believe you have to:
1. fork my repository by going to my project page and pressing "Fork" button which should be somewhere on top 
2. create a new branch called e.g. "temporary-minimap-position"
3. commit and push
4. go to https://github.com/YOUR_USER_NAME/REPOSITORY_NAME/branches
5. find the branch in "Your branches" section
6. press "New Pull Request"

Greetings,
Andrzej

**Comment by andrzejkrecicki** [comment]
Dear @AquaJerry since the issue was left open for 2 years and no action was done I have no choice but to close it.
Temporary mini-map HTML element will no longer exist as it got just replaced with its proper successor implemented the same way as every other visual element and will be drawn on canvas directly. See [6c34471397aeb580d68cb517a7e825e67be94793](https://github.com/andrzejkrecicki/epoch-of-emperors/commit/6c34471397aeb580d68cb517a7e825e67be94793) for more details.
